name: Sync resource-parser.js, check.js, and net-lsp-x.js

on:
  schedule:
    # 每天 UTC 时间0点0分运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 手动触发

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch the latest resource-parser.js
        run: curl -o general/resource-parser.js https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js

      - name: Fetch the latest check.js
        run: curl -o task/check.js https://raw.githubusercontent.com/MCdasheng/QuantumultX/main/Streaming/check.js

      - name: Fetch the latest net-lsp-x.js
        run: curl -o task/net-lsp-x.js https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            echo "::set-output name=changed::false"
          else
            echo "Changes detected"
            echo "::set-output name=changed::true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add general/resource-parser.js task/check.js task/net-lsp-x.js
          git commit -m 'Update resource-parser.js, check.js, and net-lsp-x.js'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
